language: csharp
dist: trusty
sudo: required

matrix:
  include:
    - dotnet: 1.0.0-preview2-003131
      mono: latest
      env: DOTNETCORE=1
install:
 - dotnet restore

script:
 - dotnet build
 - dotnet pack -o ./release

deploy:
 provider: script
 skip_cleanup: true
 script:
   - nuget push release/*.nupkg -ApiKey $NUGET_API_KEY
 on:
    branch: master

