language: csharp
dist: trusty
sudo: required

matrix:
  include:
    - dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
install:
 - dotnet restore

script:
 - dotnet build -f netstandard16

deploy:
 provider: script
 skip_cleanup: true
 script:
  - dotnet pack -o ./release && nuget push release/*.nupkg $NUGET_API_KEY
 on:
    branch: master

