language: csharp
#dist: xenial
matrix:
  include:
    - dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
    - mono: latest
install:
 - dotnet restore

script:
 - dotnet build

deploy:
 provider: script
 skip_cleanup: true
 script:
  - dotnet pack -o ./release && cd release && nuget push *.nupkg $NUGET_API_KEY
 on:
    branch: master

